name: SonarCloud Scan
on:
  push:
    branches: [ main ]
jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v6
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: https://sonarcloud.io
        with:
          args: >
            -Dsonar.projectKey=Arsh-ush_dvwa-analysis
            -Dsonar.organization=arsh-ush
            -Dsonar.sources=.
            -Dsonar.language=php
            -Dsonar.sourceEncoding=UTF-8
